
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.sql.DriverManager;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frame2.java
 *
 * Created on Nov 2, 2015, 10:51:31 AM
 */

/**
 *
 * @author suvranjan
 */
public class frame2 extends javax.swing.JFrame {

    /** Creates new form frame2 */
    public frame2() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        t2 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setText(" regno");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(90, 80, 70, 14);

        jButton2.setText(" Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(190, 290, 90, 23);
        jPanel1.add(t2);
        t2.setBounds(190, 110, 100, 20);
        jPanel1.add(t4);
        t4.setBounds(190, 190, 100, 20);

        jButton1.setText(" Insert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(50, 290, 80, 23);

        jLabel4.setText(" Marks");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(90, 190, 70, 14);

        jLabel5.setText(" ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(90, 270, 3, 14);
        jPanel1.add(t1);
        t1.setBounds(190, 80, 100, 20);
        jPanel1.add(t3);
        t3.setBounds(190, 150, 100, 20);

        jLabel3.setText(" Class");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(90, 150, 60, 14);

        jLabel2.setText(" Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(90, 110, 70, 14);

        jButton3.setText(" Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(323, 290, 80, 23);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/20110402_Java Cream resized.jpg"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 0, 460, 340);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        t1.setText("");
        t2.setText("");
        t3.setText("");
        t4.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String regno=t1.getText();
        String name =t2.getText();
        String c=t3.getText();

        String m = t4.getText();
        Connection conn=null;
        PreparedStatement pstmt=null;
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            conn=   (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/school","root","sql");
            pstmt=  (PreparedStatement) conn.prepareStatement("insert into student values(?,?,?,?)");
            pstmt.setString(1,regno);
            pstmt.setString(2,name);
            pstmt.setString(3,c);
            pstmt.setString(4,m);
            int i = pstmt.executeUpdate();
            if(i>0)
            {
                JOptionPane.showMessageDialog(this,"Record Inserted Successfully!!!!");
            }
            else
            JOptionPane.showMessageDialog(this,"Record NOT Inserted!!!!");

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        super.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    // End of variables declaration//GEN-END:variables

}
